server:
  port: ${APP_PORT:9200}
spring:
  application.name: customers-service
  datasource:
    url: jdbc:h2:file:./data/customers-db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate.ddl-auto: update
    defer-datasource-initialization: true
    open-in-view: false
    show-sql: false
  sql.init.mode: always
  h2.console.enabled: ${H2_CONSOLE_ENABLED:true}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP:customers-events-consumer}
      max-attempts: 5
      properties.spring.json.trusted.packages: net.wowdev.ecommerce.domain.dto
    producer:
      acks: all
      retries: 5
      properties.enable.idempotence: true
app.kafka.customer-changes-topic: ${KAFKA_CUSTOMER_CHANGES_TOPIC:customer-change-topic}
